[package]
name = "alloy-proto"
version = "0.2.0"
edition = "2024"
build = "build.rs"

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = "0.12"
